image: nixos/nix:latest

.build_blog_template: &build_blog
  script:
    - nix-shell --run "hugo"

build:
  <<: *build_blog
  except:
    - main

pages:
  <<: *build_blog
  only:
    - main
  artifacts:
    paths:
      - public
