image: python:3.6-alpine

pages:
  only:
    - master
  script:
    - apk add --no-cache --virtual git
    - git clone https://github.com/alexandrevicenzi/Flex.git /tmp/flex-pelican-theme -q
    - pip install -r requirements.txt
    - pelican -s publishconf.py
  artifacts:
    paths:
      - public/

