image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.build_blog_template: &build_blog
  script:
    - hugo

build:
  <<: *build_blog
  except:
    - main

pages:
  <<: *build_blog
  only:
    - main
  artifacts:
    paths:
      - public
