---
name: ci

on:
  push:
    branches: [ main ]

jobs:
  ci:
    name: build site
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2.3.5

    - name: setup nix
      uses: cachix/install-nix-action@v14.1

    - name: build
      run: nix-shell --run "hugo"

    - name: deploy
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
        keep_history: false
        fqdn: jesusmtnez.es
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
