---
name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"

jobs:
  ci:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2

    - name: "Install Nix ❄️"
      uses: cachix/install-nix-action@v17

    - name: "Build 🛠️"
      run: "nix develop -c hugo"

    - name: "Deploy 🚀"
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: public
        keep_history: false
        fqdn: jesusmtnez.es
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
