---
name: ci

on:
  push:
    branches: [ main ]
    paths-ignore: [ "README.md" ]
  pull_request:
    paths-ignore: [ "README.md" ]

jobs:
  ci:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: "Install Nix ❄️"
      uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28 # v25

    - name: "Build 🛠️"
      run: "nix build"

    - name: "Deploy 🚀"
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: crazy-max/ghaction-github-pages@v4.0.0
      with:
        target_branch: gh-pages
        build_dir: result
        follow_symlinks: true
        keep_history: false
        fqdn: jesusmtnez.es
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
